TANS:
  title_abstract:
    cora:
      hidden_dim: 128
      num_layers: 2
      normalize: none
      lr: 0.001
      decay: 0.0001
      dropout: 0.8
    pubmed:
      hidden_dim: 256
      num_layers: 2
      normalize: none
      lr: 0.005
      decay: 0.0005
      dropout: 0.1
  title:
    cora:
      hidden_dim: 256
      num_layers: 3
      normalize: none
      lr: 0.001
      decay: 0.00005
      dropout: 0.8
    pubmed:
      hidden_dim: 128
      num_layers: 2
      normalize: none
      lr: 0.001
      decay: 0.00005
      dropout: 0.5
  usa:
    hidden_dim: 128
    num_layers: 3
    normalize: none
    lr: 0.05
    decay: 0.0001
    dropout: 0.1
  brazil:
    num_layers: 3
    normalize: none
    lr: 0.005
    decay: 0.0001
    dropout: 0.5
    train_num: 10
    val_num: 20
  europe:
    hidden_dim: 256
    num_layers: 2
    normalize: none
    lr: 0.001
    decay: 0.00005
    dropout: 0.5